# Generated by Django 6.0.2 on 2026-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BRAZIL", "Brasil"),
                            ("ARGENTINA", "Argentina"),
                            ("CHILE", "Chile"),
                            ("URUGUAY", "Uruguai"),
                            ("PARAGUAY", "Paraguai"),
                            ("UNITED_STATES", "Estados Unidos"),
                            ("CANADA", "Canadá"),
                            ("MEXICO", "México"),
                            ("PORTUGAL", "Portugal"),
                            ("SPAIN", "Espanha"),
                            ("FRANCE", "França"),
                            ("GERMANY", "Alemanha"),
                            ("ITALY", "Itália"),
                            ("UNITED_KINGDOM", "Reino Unido"),
                            ("JAPAN", "Japão"),
                            ("CHINA", "China"),
                            ("INDIA", "Índia"),
                            ("AUSTRALIA", "Austrália"),
                            ("SOUTH_AFRICA", "África do Sul"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
